const whichEmotionToShow = [
  "You are incredibly happy",
  "You are very angry",
  "You are in love",
  "You are scared",
  "You are shocked",
  "You are bored",
  "You are proud of yourself",
  "You are upset",
  "You are confused",
  "You are surprised",
  "You feel disgusted",
  "You are jealous",
  "You are nervous before a performance",
  "You just won the lottery",
  "You lost and are trying not to cry",
  "You are trying to remember something",
  "You do not believe what you are seeing",
  "You are very tired",
  "You want to sleep",
  "You are waiting for someone who is late",
  "You are cold",
  "You are hot",
  "You are hungry",
  "You are full to the brim",
  "You saw something disgusting",
  "You heard something incredible",
  "You are trying to be serious, but you want to laugh",
  "You are offended by someone",
  "You are pretending not to be guilty",
  "You are afraid to say something",
  "You are delighted",
  "You have just saw a ghost",
  "You heard a scary sound",
  "You saw your ex",
  "You saw a celebrity you adore",
  "You are hiding a secret",
  "You just told a lie",
  "You are disappointed in someone",
  "You are inspired",
  "You are focused",
  "You want to impress someone",
  "You are panicking",
  "You are late",
  "You just dropped something",
  "You are looking for something in the dark",
  "You woke up in the wrong place",
  "You feel ashamed",
  "You are pretending to understand",
  "You want to hide",
  "You don't understand what is happening",
  "You are shocked by the price",
  "You received a compliment",
  "You heard a stupid gossip",
  "You are trying not to laugh",
  "You are trying to look smart",
  "You are pretending to be having fun",
  "You are self-absorbed",
  "You are trying to convince someone",
  "You are listening to a boring story",
  "You are annoyed by trifle",
  "You are delighted with the music",
  "You dance as if no one is watching",
  "You are nervous before a date",
  "You are shy",
  "You want to seem brave",
  "You are surprised by your friend's behavior",
  "You are proud of your friend",
  "You are trying not to cry",
  "You are afraid of the dark",
  "You see something beautiful",
  "You are confident in yourself",
  "You want everyone to listen to you",
  "You joke and wait for a reaction",
  "You did not understand something and pretend that you understood",
  "You are nervously waiting for the results",
  "You look thoughtfully into the distance",
  "You sneeze",
  "You are scared",
  "You check if anyone is watching",
  "You accidentally did something funny",
  "You were happy with a gift",
  "You are angry with yourself",
  "You are looking for a way out of the situation",
  "You fell and pretend that everything is okay",
  "You saw someone strange",
  "You want something eat secretly",
  "You are trying to attract attention",
  "You are suddenly scared",
  "You have won a competition",
  "You are preparing a surprise",
  "You are pretending to be indifferent",
  "You are trying to hide your laughter",
  "You are feeling proud of yourself",
  "You are missing someone",
  "You have just remembered something",
  "You cannot concentrate",
  "You want to run away",
  "You are hiding your joy",
  "You are trying not to break down",
  "You have just realized that you have won"
];

module.exports = whichEmotionToShow;
